GET http://localhost:3000/user HTTP/1.1

###

GET http://localhost:3000/user/636f449d742999d65e06a021 HTTP/1.1

###

PUT  http://localhost:3000/user/636f449d742999d65e06a021 HTTP/1.1
Content-Type: application/json

{
    "username": "Badguy",
    "email": "ty@yahoo.com"
}